
package Vista;

import Controlador.objetoPerdidoControlador;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.table.DefaultTableModel;
import Controlador.eliminarDato;

/**
 *
 * @author Diego Cabrera
 */
public class JFRM_listaObjetos extends javax.swing.JFrame {

    /**
     * Creates new form JFRM_listaObjetos
     */
    public JFRM_listaObjetos() {
        initComponents();
        this.setLocationRelativeTo(null);
        cargarDatos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        JTBL_listaObjetos = new javax.swing.JTable();
        JBTN_volverMenuPrincipal = new javax.swing.JButton();
        JBTN_borrarDatos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Lista de objetos perdidos");

        JTBL_listaObjetos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID Objeto", "Nombre Objeto", "Descripcion", "Categoria", "Lugar encontrado", "Estado"
            }
        ));
        jScrollPane1.setViewportView(JTBL_listaObjetos);

        JBTN_volverMenuPrincipal.setText("Volver a menu principal");
        JBTN_volverMenuPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBTN_volverMenuPrincipalActionPerformed(evt);
            }
        });

        JBTN_borrarDatos.setText("Eliminar Dato");
        JBTN_borrarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBTN_borrarDatosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(JBTN_volverMenuPrincipal)
                        .addGap(84, 84, 84)
                        .addComponent(JBTN_borrarDatos))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 676, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JBTN_volverMenuPrincipal)
                    .addComponent(JBTN_borrarDatos))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cargarDatos(){
        DefaultTableModel modeloTabla = (DefaultTableModel) JTBL_listaObjetos.getModel();
        objetoPerdidoControlador controlador = new objetoPerdidoControlador();
        controlador.obtenerListaObjetos().forEach(objeto -> {
            modeloTabla.addRow(new Object[] {
                objeto.getIdObjeto(),
                objeto.getNombreObjeto(),
                objeto.getDescObjeto(),
                objeto.getCategoria(),
                objeto.getLugarEncontrado(),
                objeto.getEstadoObjeto()
            });
        });
        
        
    }
    
    
    
    private void JBTN_volverMenuPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBTN_volverMenuPrincipalActionPerformed
        JFRM_menuPrincipal menuPrincipal = new JFRM_menuPrincipal();
        menuPrincipal.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_JBTN_volverMenuPrincipalActionPerformed

    private void JBTN_borrarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBTN_borrarDatosActionPerformed
        
   //aqui debiese ir el boton de borrado PERO NO ME SALIOOOO  
    }//GEN-LAST:event_JBTN_borrarDatosActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(JFRM_listaObjetos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(JFRM_listaObjetos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(JFRM_listaObjetos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(JFRM_listaObjetos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new JFRM_listaObjetos().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBTN_borrarDatos;
    private javax.swing.JButton JBTN_volverMenuPrincipal;
    private javax.swing.JTable JTBL_listaObjetos;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
