
package Vista;

import Controlador.entregaObjetoControlador;
import Modelo.Reclamante;
import javax.swing.JOptionPane;

/**
 *
 * @author Diego Cabrera
 */
public class JFRM_entregarObjeto extends javax.swing.JFrame {

    /**
     * Creates new form JFRM_entregarObjeto
     */
    public JFRM_entregarObjeto() {
        initComponents();
        this.setLocationRelativeTo(null);
        JBTN_registrarEntrega.addActionListener(evt -> registrarEntrega());

        //cargarObjetos(); //para el comboBox
    }

    
    
    
        
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JLBL_idObjeto = new javax.swing.JLabel();
        JCBX_idObjeto = new javax.swing.JComboBox<>();
        JLBL_nombreReclamante = new javax.swing.JLabel();
        JTXTF_nombreReclamante = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        JTXTF_apellidoReclamante = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        JTXTF_telefonoReclamante = new javax.swing.JTextField();
        JLBL_emailReclamante = new javax.swing.JLabel();
        JTXTF_emailReclamante = new javax.swing.JTextField();
        JBTN_registrarEntrega = new javax.swing.JButton();
        JBTN_volverMenuPrincipal = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JLBL_idObjeto.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        JLBL_idObjeto.setText("ID Objeto a devolver:");

        JCBX_idObjeto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        JLBL_nombreReclamante.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        JLBL_nombreReclamante.setText("Nombre reclamante:");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel1.setText("Apellido reclamante:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel2.setText("Telefono:");

        JLBL_emailReclamante.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        JLBL_emailReclamante.setText("Email:");

        JBTN_registrarEntrega.setText("Registrar entrega");
        JBTN_registrarEntrega.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBTN_registrarEntregaActionPerformed(evt);
            }
        });

        JBTN_volverMenuPrincipal.setText("Volver al menu principal");
        JBTN_volverMenuPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBTN_volverMenuPrincipalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(JLBL_emailReclamante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(JLBL_nombreReclamante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(JLBL_idObjeto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addComponent(JCBX_idObjeto, 0, 127, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addComponent(JTXTF_nombreReclamante))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JTXTF_telefonoReclamante, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(JTXTF_apellidoReclamante)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addComponent(JTXTF_emailReclamante))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(JBTN_volverMenuPrincipal)
                        .addGap(46, 46, 46)
                        .addComponent(JBTN_registrarEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(89, 89, 89))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLBL_idObjeto)
                    .addComponent(JCBX_idObjeto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLBL_nombreReclamante)
                    .addComponent(JTXTF_nombreReclamante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(JTXTF_apellidoReclamante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(JTXTF_telefonoReclamante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLBL_emailReclamante)
                    .addComponent(JTXTF_emailReclamante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(JBTN_volverMenuPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                    .addComponent(JBTN_registrarEntrega, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(46, 46, 46))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    private void registrarEntrega(){
        String nombre = JTXTF_nombreReclamante.getText();
        String apellido = JTXTF_apellidoReclamante.getText();
        String telefono = JTXTF_telefonoReclamante.getText();
        String email = JTXTF_emailReclamante.getText();
        int idObjeto = obtenerIdObjetoSeleccionado();
        
        if (nombre.isEmpty() || apellido.isEmpty() || telefono.isEmpty() || email.isEmpty() || idObjeto == -1) {
            JOptionPane.showMessageDialog(this, "Por favor, completa todos los campos.");
            return;
    } else {
        // Crear un objeto Reclamante
        Reclamante reclamante = new Reclamante();
        reclamante.setNombre(nombre);
        reclamante.setApellido(apellido);
        reclamante.setTelefono(telefono);
        reclamante.setEmail(email);
        
        entregaObjetoControlador controlador = new entregaObjetoControlador();
        boolean exito = controlador.registrarEntrega(idObjeto, reclamante);
        
        if (exito){
            JOptionPane.showMessageDialog(this, "Se ha registrado la entrega con exito!!");
        }else{
            JOptionPane.showMessageDialog(this,"Error al registrar entrega, intente de nuevo por favor");
        }
        
    }
  }    
    
    
    private int obtenerIdObjetoSeleccionado() {
        // Obtener el ID del objeto seleccionado en el JComboBox
        String seleccionado = (String) JCBX_idObjeto.getSelectedItem();
        if (seleccionado != null && !seleccionado.isEmpty()) {
            return Integer.parseInt(seleccionado.split(" - ")[0]); // Supongamos que el formato es "ID - Nombre"
        }
        return -1; // Retorna -1 si no hay un objeto seleccionado
    }

    
    
    
    private void JBTN_volverMenuPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBTN_volverMenuPrincipalActionPerformed
        JFRM_menuPrincipal menuPrincipal = new JFRM_menuPrincipal();
        menuPrincipal.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_JBTN_volverMenuPrincipalActionPerformed

    private void JBTN_registrarEntregaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBTN_registrarEntregaActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_JBTN_registrarEntregaActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(JFRM_entregarObjeto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(JFRM_entregarObjeto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(JFRM_entregarObjeto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(JFRM_entregarObjeto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new JFRM_entregarObjeto().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBTN_registrarEntrega;
    private javax.swing.JButton JBTN_volverMenuPrincipal;
    private javax.swing.JComboBox<String> JCBX_idObjeto;
    private javax.swing.JLabel JLBL_emailReclamante;
    private javax.swing.JLabel JLBL_idObjeto;
    private javax.swing.JLabel JLBL_nombreReclamante;
    private javax.swing.JTextField JTXTF_apellidoReclamante;
    private javax.swing.JTextField JTXTF_emailReclamante;
    private javax.swing.JTextField JTXTF_nombreReclamante;
    private javax.swing.JTextField JTXTF_telefonoReclamante;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
