
package Vista;

import Controlador.objetoPerdidoControlador;
import javax.swing.JOptionPane;

/**
 *
 * @author Diego Cabrera
 */
public class JFRM_registrarObjeto extends javax.swing.JFrame {

    /**
     * Creates new form JFRM_registrarObjeto
     */
    public JFRM_registrarObjeto() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        JBTN_registrarObjeto.addActionListener(evt -> registrarObjeto());
        
    }

    private void registrarObjeto(){
        
        String nombre = JTXTF_nombreObjeto.getText();
        String descripcion = JTXTF_descripcionObjeto.getText();
        String categoria = (String) JCBX_categoria.getSelectedItem();
        String lugarEncontrado = JTXTF_lugarEncontrado.getText();
        String estado = "almacenado";
        
        if (nombre.isEmpty() || descripcion.isEmpty() || lugarEncontrado.isEmpty()) {
            System.out.println("Por favor complete todos los campos!!");
                  
        } else {
            objetoPerdidoControlador controlador = new objetoPerdidoControlador();
            boolean exito = controlador.registrarObjeto(nombre, descripcion, categoria, lugarEncontrado, estado);
            
            if (exito) { 
                System.out.println("Objeto registrado!!");
                JOptionPane.showMessageDialog(this, "Objeto registrado!!");
                
                //dejar limpio para registrar otro
                JTXTF_nombreObjeto.setText("");
                JTXTF_descripcionObjeto.setText("");
                JCBX_categoria.setSelectedIndex(0);
                JTXTF_lugarEncontrado.setText("");
            } else {
                System.out.println("Error!! Volver a registrar objeto!");
                JOptionPane.showMessageDialog(this, "Error, favor volver a registrar objeto!!");
            }
        }
        
    }
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JLBL_nombreObjeto = new javax.swing.JLabel();
        JLBL_descripcionObjeto = new javax.swing.JLabel();
        JLBL_categoria = new javax.swing.JLabel();
        JLBL_lugarEncontrado = new javax.swing.JLabel();
        JTXTF_nombreObjeto = new javax.swing.JTextField();
        JTXTF_descripcionObjeto = new javax.swing.JTextField();
        JTXTF_lugarEncontrado = new javax.swing.JTextField();
        JCBX_categoria = new javax.swing.JComboBox<>();
        JBTN_registrarObjeto = new javax.swing.JButton();
        JBTN_volverMenuPrincipal = new javax.swing.JButton();
        JLBL_tituloRegistroObjeto = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registro de objeto perdido");

        JLBL_nombreObjeto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        JLBL_nombreObjeto.setText("Nombre del objeto:");

        JLBL_descripcionObjeto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        JLBL_descripcionObjeto.setText("Descripcion:");

        JLBL_categoria.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        JLBL_categoria.setText("Categoria:");

        JLBL_lugarEncontrado.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        JLBL_lugarEncontrado.setText("Lugar encontrado:");

        JTXTF_nombreObjeto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        JTXTF_descripcionObjeto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        JTXTF_descripcionObjeto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTXTF_descripcionObjetoActionPerformed(evt);
            }
        });

        JTXTF_lugarEncontrado.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        JTXTF_lugarEncontrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTXTF_lugarEncontradoActionPerformed(evt);
            }
        });

        JCBX_categoria.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        JCBX_categoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ropa", "Electronico", "Tarjeta", "Personal" }));

        JBTN_registrarObjeto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        JBTN_registrarObjeto.setText("Registrar");
        JBTN_registrarObjeto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBTN_registrarObjetoActionPerformed(evt);
            }
        });

        JBTN_volverMenuPrincipal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        JBTN_volverMenuPrincipal.setText("Volver al menu principal");
        JBTN_volverMenuPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBTN_volverMenuPrincipalActionPerformed(evt);
            }
        });

        JLBL_tituloRegistroObjeto.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        JLBL_tituloRegistroObjeto.setText("Registro de objeto perdido");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addComponent(JLBL_tituloRegistroObjeto, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(JLBL_nombreObjeto)
                            .addComponent(JLBL_descripcionObjeto)
                            .addComponent(JLBL_categoria)
                            .addComponent(JLBL_lugarEncontrado))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(JTXTF_nombreObjeto)
                            .addComponent(JTXTF_descripcionObjeto)
                            .addComponent(JCBX_categoria, 0, 200, Short.MAX_VALUE)
                            .addComponent(JTXTF_lugarEncontrado)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(JBTN_volverMenuPrincipal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, Short.MAX_VALUE)
                        .addComponent(JBTN_registrarObjeto, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JLBL_tituloRegistroObjeto)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLBL_nombreObjeto)
                    .addComponent(JTXTF_nombreObjeto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLBL_descripcionObjeto)
                    .addComponent(JTXTF_descripcionObjeto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLBL_categoria)
                    .addComponent(JCBX_categoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLBL_lugarEncontrado)
                    .addComponent(JTXTF_lugarEncontrado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JBTN_volverMenuPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JBTN_registrarObjeto, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JTXTF_descripcionObjetoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTXTF_descripcionObjetoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTXTF_descripcionObjetoActionPerformed

    private void JTXTF_lugarEncontradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTXTF_lugarEncontradoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTXTF_lugarEncontradoActionPerformed

    private void JBTN_registrarObjetoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBTN_registrarObjetoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JBTN_registrarObjetoActionPerformed

    private void JBTN_volverMenuPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBTN_volverMenuPrincipalActionPerformed
        JFRM_menuPrincipal menuPrincipal = new JFRM_menuPrincipal();
        menuPrincipal.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_JBTN_volverMenuPrincipalActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(JFRM_registrarObjeto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(JFRM_registrarObjeto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(JFRM_registrarObjeto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(JFRM_registrarObjeto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new JFRM_registrarObjeto().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBTN_registrarObjeto;
    private javax.swing.JButton JBTN_volverMenuPrincipal;
    private javax.swing.JComboBox<String> JCBX_categoria;
    private javax.swing.JLabel JLBL_categoria;
    private javax.swing.JLabel JLBL_descripcionObjeto;
    private javax.swing.JLabel JLBL_lugarEncontrado;
    private javax.swing.JLabel JLBL_nombreObjeto;
    private javax.swing.JLabel JLBL_tituloRegistroObjeto;
    private javax.swing.JTextField JTXTF_descripcionObjeto;
    private javax.swing.JTextField JTXTF_lugarEncontrado;
    private javax.swing.JTextField JTXTF_nombreObjeto;
    // End of variables declaration//GEN-END:variables
}
