
package Vista;

/**
 *
 * @author Diego Cabrera
 */
public class JFRM_menuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form JFRM_menuPrincipal
     */
    public JFRM_menuPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JLBL_tituloMenuPrincipal = new javax.swing.JLabel();
        JBTN_registroObjeto = new javax.swing.JButton();
        JBTN_listaObjetos = new javax.swing.JButton();
        JBTN_entregarObjeto = new javax.swing.JButton();
        JBTN_cerrarSesion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Principal");

        JLBL_tituloMenuPrincipal.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        JLBL_tituloMenuPrincipal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLBL_tituloMenuPrincipal.setText("Menu principal");

        JBTN_registroObjeto.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        JBTN_registroObjeto.setText("Registrar objeto");
        JBTN_registroObjeto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBTN_registroObjetoActionPerformed(evt);
            }
        });

        JBTN_listaObjetos.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        JBTN_listaObjetos.setText("Ver lista de objetos");
        JBTN_listaObjetos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBTN_listaObjetosActionPerformed(evt);
            }
        });

        JBTN_entregarObjeto.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        JBTN_entregarObjeto.setText("Entregar objeto");
        JBTN_entregarObjeto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBTN_entregarObjetoActionPerformed(evt);
            }
        });

        JBTN_cerrarSesion.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        JBTN_cerrarSesion.setText("Cerrar sesion");
        JBTN_cerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBTN_cerrarSesionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 108, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(JBTN_listaObjetos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JBTN_registroObjeto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JBTN_entregarObjeto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JBTN_cerrarSesion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JLBL_tituloMenuPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(114, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JLBL_tituloMenuPrincipal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(JBTN_registroObjeto, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(JBTN_listaObjetos, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(JBTN_entregarObjeto, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(JBTN_cerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBTN_listaObjetosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBTN_listaObjetosActionPerformed
        JFRM_listaObjetos listaObjeto = new JFRM_listaObjetos();
        listaObjeto.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_JBTN_listaObjetosActionPerformed

    private void JBTN_registroObjetoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBTN_registroObjetoActionPerformed
        JFRM_registrarObjeto registroObjeto = new JFRM_registrarObjeto();
        registroObjeto.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_JBTN_registroObjetoActionPerformed

    private void JBTN_entregarObjetoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBTN_entregarObjetoActionPerformed
        JFRM_entregarObjeto entregarObjeto = new JFRM_entregarObjeto();
        entregarObjeto.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_JBTN_entregarObjetoActionPerformed

    private void JBTN_cerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBTN_cerrarSesionActionPerformed
        JFRM_Login login = new JFRM_Login();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_JBTN_cerrarSesionActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(JFRM_menuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(JFRM_menuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(JFRM_menuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(JFRM_menuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new JFRM_menuPrincipal().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBTN_cerrarSesion;
    private javax.swing.JButton JBTN_entregarObjeto;
    private javax.swing.JButton JBTN_listaObjetos;
    private javax.swing.JButton JBTN_registroObjeto;
    private javax.swing.JLabel JLBL_tituloMenuPrincipal;
    // End of variables declaration//GEN-END:variables
}
